require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe AddFuelsController do

  # This should return the minimal set of attributes required to create a valid
  # AddFuel. As you add validations to AddFuel, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "unit_fuel_id" => "1" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # AddFuelsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all add_fuels as @add_fuels" do
      add_fuel = AddFuel.create! valid_attributes
      get :index, {}, valid_session
      assigns(:add_fuels).should eq([add_fuel])
    end
  end

  describe "GET show" do
    it "assigns the requested add_fuel as @add_fuel" do
      add_fuel = AddFuel.create! valid_attributes
      get :show, {:id => add_fuel.to_param}, valid_session
      assigns(:add_fuel).should eq(add_fuel)
    end
  end

  describe "GET new" do
    it "assigns a new add_fuel as @add_fuel" do
      get :new, {}, valid_session
      assigns(:add_fuel).should be_a_new(AddFuel)
    end
  end

  describe "GET edit" do
    it "assigns the requested add_fuel as @add_fuel" do
      add_fuel = AddFuel.create! valid_attributes
      get :edit, {:id => add_fuel.to_param}, valid_session
      assigns(:add_fuel).should eq(add_fuel)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new AddFuel" do
        expect {
          post :create, {:add_fuel => valid_attributes}, valid_session
        }.to change(AddFuel, :count).by(1)
      end

      it "assigns a newly created add_fuel as @add_fuel" do
        post :create, {:add_fuel => valid_attributes}, valid_session
        assigns(:add_fuel).should be_a(AddFuel)
        assigns(:add_fuel).should be_persisted
      end

      it "redirects to the created add_fuel" do
        post :create, {:add_fuel => valid_attributes}, valid_session
        response.should redirect_to(AddFuel.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved add_fuel as @add_fuel" do
        # Trigger the behavior that occurs when invalid params are submitted
        AddFuel.any_instance.stub(:save).and_return(false)
        post :create, {:add_fuel => { "unit_fuel_id" => "invalid value" }}, valid_session
        assigns(:add_fuel).should be_a_new(AddFuel)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        AddFuel.any_instance.stub(:save).and_return(false)
        post :create, {:add_fuel => { "unit_fuel_id" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested add_fuel" do
        add_fuel = AddFuel.create! valid_attributes
        # Assuming there are no other add_fuels in the database, this
        # specifies that the AddFuel created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        AddFuel.any_instance.should_receive(:update).with({ "unit_fuel_id" => "1" })
        put :update, {:id => add_fuel.to_param, :add_fuel => { "unit_fuel_id" => "1" }}, valid_session
      end

      it "assigns the requested add_fuel as @add_fuel" do
        add_fuel = AddFuel.create! valid_attributes
        put :update, {:id => add_fuel.to_param, :add_fuel => valid_attributes}, valid_session
        assigns(:add_fuel).should eq(add_fuel)
      end

      it "redirects to the add_fuel" do
        add_fuel = AddFuel.create! valid_attributes
        put :update, {:id => add_fuel.to_param, :add_fuel => valid_attributes}, valid_session
        response.should redirect_to(add_fuel)
      end
    end

    describe "with invalid params" do
      it "assigns the add_fuel as @add_fuel" do
        add_fuel = AddFuel.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        AddFuel.any_instance.stub(:save).and_return(false)
        put :update, {:id => add_fuel.to_param, :add_fuel => { "unit_fuel_id" => "invalid value" }}, valid_session
        assigns(:add_fuel).should eq(add_fuel)
      end

      it "re-renders the 'edit' template" do
        add_fuel = AddFuel.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        AddFuel.any_instance.stub(:save).and_return(false)
        put :update, {:id => add_fuel.to_param, :add_fuel => { "unit_fuel_id" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested add_fuel" do
      add_fuel = AddFuel.create! valid_attributes
      expect {
        delete :destroy, {:id => add_fuel.to_param}, valid_session
      }.to change(AddFuel, :count).by(-1)
    end

    it "redirects to the add_fuels list" do
      add_fuel = AddFuel.create! valid_attributes
      delete :destroy, {:id => add_fuel.to_param}, valid_session
      response.should redirect_to(add_fuels_url)
    end
  end

end
