require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe ExternalIssuedsController do

  # This should return the minimal set of attributes required to create a valid
  # ExternalIssued. As you add validations to ExternalIssued, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "unit_fuel_id" => "1" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # ExternalIssuedsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all external_issueds as @external_issueds" do
      external_issued = ExternalIssued.create! valid_attributes
      get :index, {}, valid_session
      assigns(:external_issueds).should eq([external_issued])
    end
  end

  describe "GET show" do
    it "assigns the requested external_issued as @external_issued" do
      external_issued = ExternalIssued.create! valid_attributes
      get :show, {:id => external_issued.to_param}, valid_session
      assigns(:external_issued).should eq(external_issued)
    end
  end

  describe "GET new" do
    it "assigns a new external_issued as @external_issued" do
      get :new, {}, valid_session
      assigns(:external_issued).should be_a_new(ExternalIssued)
    end
  end

  describe "GET edit" do
    it "assigns the requested external_issued as @external_issued" do
      external_issued = ExternalIssued.create! valid_attributes
      get :edit, {:id => external_issued.to_param}, valid_session
      assigns(:external_issued).should eq(external_issued)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new ExternalIssued" do
        expect {
          post :create, {:external_issued => valid_attributes}, valid_session
        }.to change(ExternalIssued, :count).by(1)
      end

      it "assigns a newly created external_issued as @external_issued" do
        post :create, {:external_issued => valid_attributes}, valid_session
        assigns(:external_issued).should be_a(ExternalIssued)
        assigns(:external_issued).should be_persisted
      end

      it "redirects to the created external_issued" do
        post :create, {:external_issued => valid_attributes}, valid_session
        response.should redirect_to(ExternalIssued.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved external_issued as @external_issued" do
        # Trigger the behavior that occurs when invalid params are submitted
        ExternalIssued.any_instance.stub(:save).and_return(false)
        post :create, {:external_issued => { "unit_fuel_id" => "invalid value" }}, valid_session
        assigns(:external_issued).should be_a_new(ExternalIssued)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        ExternalIssued.any_instance.stub(:save).and_return(false)
        post :create, {:external_issued => { "unit_fuel_id" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested external_issued" do
        external_issued = ExternalIssued.create! valid_attributes
        # Assuming there are no other external_issueds in the database, this
        # specifies that the ExternalIssued created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        ExternalIssued.any_instance.should_receive(:update).with({ "unit_fuel_id" => "1" })
        put :update, {:id => external_issued.to_param, :external_issued => { "unit_fuel_id" => "1" }}, valid_session
      end

      it "assigns the requested external_issued as @external_issued" do
        external_issued = ExternalIssued.create! valid_attributes
        put :update, {:id => external_issued.to_param, :external_issued => valid_attributes}, valid_session
        assigns(:external_issued).should eq(external_issued)
      end

      it "redirects to the external_issued" do
        external_issued = ExternalIssued.create! valid_attributes
        put :update, {:id => external_issued.to_param, :external_issued => valid_attributes}, valid_session
        response.should redirect_to(external_issued)
      end
    end

    describe "with invalid params" do
      it "assigns the external_issued as @external_issued" do
        external_issued = ExternalIssued.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        ExternalIssued.any_instance.stub(:save).and_return(false)
        put :update, {:id => external_issued.to_param, :external_issued => { "unit_fuel_id" => "invalid value" }}, valid_session
        assigns(:external_issued).should eq(external_issued)
      end

      it "re-renders the 'edit' template" do
        external_issued = ExternalIssued.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        ExternalIssued.any_instance.stub(:save).and_return(false)
        put :update, {:id => external_issued.to_param, :external_issued => { "unit_fuel_id" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested external_issued" do
      external_issued = ExternalIssued.create! valid_attributes
      expect {
        delete :destroy, {:id => external_issued.to_param}, valid_session
      }.to change(ExternalIssued, :count).by(-1)
    end

    it "redirects to the external_issueds list" do
      external_issued = ExternalIssued.create! valid_attributes
      delete :destroy, {:id => external_issued.to_param}, valid_session
      response.should redirect_to(external_issueds_url)
    end
  end

end
