require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe FuelTanksController do

  # This should return the minimal set of attributes required to create a valid
  # FuelTank. As you add validations to FuelTank, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "unit_id" => "1" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # FuelTanksController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all fuel_tanks as @fuel_tanks" do
      fuel_tank = FuelTank.create! valid_attributes
      get :index, {}, valid_session
      assigns(:fuel_tanks).should eq([fuel_tank])
    end
  end

  describe "GET show" do
    it "assigns the requested fuel_tank as @fuel_tank" do
      fuel_tank = FuelTank.create! valid_attributes
      get :show, {:id => fuel_tank.to_param}, valid_session
      assigns(:fuel_tank).should eq(fuel_tank)
    end
  end

  describe "GET new" do
    it "assigns a new fuel_tank as @fuel_tank" do
      get :new, {}, valid_session
      assigns(:fuel_tank).should be_a_new(FuelTank)
    end
  end

  describe "GET edit" do
    it "assigns the requested fuel_tank as @fuel_tank" do
      fuel_tank = FuelTank.create! valid_attributes
      get :edit, {:id => fuel_tank.to_param}, valid_session
      assigns(:fuel_tank).should eq(fuel_tank)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new FuelTank" do
        expect {
          post :create, {:fuel_tank => valid_attributes}, valid_session
        }.to change(FuelTank, :count).by(1)
      end

      it "assigns a newly created fuel_tank as @fuel_tank" do
        post :create, {:fuel_tank => valid_attributes}, valid_session
        assigns(:fuel_tank).should be_a(FuelTank)
        assigns(:fuel_tank).should be_persisted
      end

      it "redirects to the created fuel_tank" do
        post :create, {:fuel_tank => valid_attributes}, valid_session
        response.should redirect_to(FuelTank.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved fuel_tank as @fuel_tank" do
        # Trigger the behavior that occurs when invalid params are submitted
        FuelTank.any_instance.stub(:save).and_return(false)
        post :create, {:fuel_tank => { "unit_id" => "invalid value" }}, valid_session
        assigns(:fuel_tank).should be_a_new(FuelTank)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        FuelTank.any_instance.stub(:save).and_return(false)
        post :create, {:fuel_tank => { "unit_id" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested fuel_tank" do
        fuel_tank = FuelTank.create! valid_attributes
        # Assuming there are no other fuel_tanks in the database, this
        # specifies that the FuelTank created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        FuelTank.any_instance.should_receive(:update).with({ "unit_id" => "1" })
        put :update, {:id => fuel_tank.to_param, :fuel_tank => { "unit_id" => "1" }}, valid_session
      end

      it "assigns the requested fuel_tank as @fuel_tank" do
        fuel_tank = FuelTank.create! valid_attributes
        put :update, {:id => fuel_tank.to_param, :fuel_tank => valid_attributes}, valid_session
        assigns(:fuel_tank).should eq(fuel_tank)
      end

      it "redirects to the fuel_tank" do
        fuel_tank = FuelTank.create! valid_attributes
        put :update, {:id => fuel_tank.to_param, :fuel_tank => valid_attributes}, valid_session
        response.should redirect_to(fuel_tank)
      end
    end

    describe "with invalid params" do
      it "assigns the fuel_tank as @fuel_tank" do
        fuel_tank = FuelTank.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        FuelTank.any_instance.stub(:save).and_return(false)
        put :update, {:id => fuel_tank.to_param, :fuel_tank => { "unit_id" => "invalid value" }}, valid_session
        assigns(:fuel_tank).should eq(fuel_tank)
      end

      it "re-renders the 'edit' template" do
        fuel_tank = FuelTank.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        FuelTank.any_instance.stub(:save).and_return(false)
        put :update, {:id => fuel_tank.to_param, :fuel_tank => { "unit_id" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested fuel_tank" do
      fuel_tank = FuelTank.create! valid_attributes
      expect {
        delete :destroy, {:id => fuel_tank.to_param}, valid_session
      }.to change(FuelTank, :count).by(-1)
    end

    it "redirects to the fuel_tanks list" do
      fuel_tank = FuelTank.create! valid_attributes
      delete :destroy, {:id => fuel_tank.to_param}, valid_session
      response.should redirect_to(fuel_tanks_url)
    end
  end

end
