require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe FuelIssuedsController do

  # This should return the minimal set of attributes required to create a valid
  # FuelIssued. As you add validations to FuelIssued, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "depot_fuel_id" => "1" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # FuelIssuedsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all fuel_issueds as @fuel_issueds" do
      fuel_issued = FuelIssued.create! valid_attributes
      get :index, {}, valid_session
      assigns(:fuel_issueds).should eq([fuel_issued])
    end
  end

  describe "GET show" do
    it "assigns the requested fuel_issued as @fuel_issued" do
      fuel_issued = FuelIssued.create! valid_attributes
      get :show, {:id => fuel_issued.to_param}, valid_session
      assigns(:fuel_issued).should eq(fuel_issued)
    end
  end

  describe "GET new" do
    it "assigns a new fuel_issued as @fuel_issued" do
      get :new, {}, valid_session
      assigns(:fuel_issued).should be_a_new(FuelIssued)
    end
  end

  describe "GET edit" do
    it "assigns the requested fuel_issued as @fuel_issued" do
      fuel_issued = FuelIssued.create! valid_attributes
      get :edit, {:id => fuel_issued.to_param}, valid_session
      assigns(:fuel_issued).should eq(fuel_issued)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new FuelIssued" do
        expect {
          post :create, {:fuel_issued => valid_attributes}, valid_session
        }.to change(FuelIssued, :count).by(1)
      end

      it "assigns a newly created fuel_issued as @fuel_issued" do
        post :create, {:fuel_issued => valid_attributes}, valid_session
        assigns(:fuel_issued).should be_a(FuelIssued)
        assigns(:fuel_issued).should be_persisted
      end

      it "redirects to the created fuel_issued" do
        post :create, {:fuel_issued => valid_attributes}, valid_session
        response.should redirect_to(FuelIssued.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved fuel_issued as @fuel_issued" do
        # Trigger the behavior that occurs when invalid params are submitted
        FuelIssued.any_instance.stub(:save).and_return(false)
        post :create, {:fuel_issued => { "depot_fuel_id" => "invalid value" }}, valid_session
        assigns(:fuel_issued).should be_a_new(FuelIssued)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        FuelIssued.any_instance.stub(:save).and_return(false)
        post :create, {:fuel_issued => { "depot_fuel_id" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested fuel_issued" do
        fuel_issued = FuelIssued.create! valid_attributes
        # Assuming there are no other fuel_issueds in the database, this
        # specifies that the FuelIssued created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        FuelIssued.any_instance.should_receive(:update).with({ "depot_fuel_id" => "1" })
        put :update, {:id => fuel_issued.to_param, :fuel_issued => { "depot_fuel_id" => "1" }}, valid_session
      end

      it "assigns the requested fuel_issued as @fuel_issued" do
        fuel_issued = FuelIssued.create! valid_attributes
        put :update, {:id => fuel_issued.to_param, :fuel_issued => valid_attributes}, valid_session
        assigns(:fuel_issued).should eq(fuel_issued)
      end

      it "redirects to the fuel_issued" do
        fuel_issued = FuelIssued.create! valid_attributes
        put :update, {:id => fuel_issued.to_param, :fuel_issued => valid_attributes}, valid_session
        response.should redirect_to(fuel_issued)
      end
    end

    describe "with invalid params" do
      it "assigns the fuel_issued as @fuel_issued" do
        fuel_issued = FuelIssued.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        FuelIssued.any_instance.stub(:save).and_return(false)
        put :update, {:id => fuel_issued.to_param, :fuel_issued => { "depot_fuel_id" => "invalid value" }}, valid_session
        assigns(:fuel_issued).should eq(fuel_issued)
      end

      it "re-renders the 'edit' template" do
        fuel_issued = FuelIssued.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        FuelIssued.any_instance.stub(:save).and_return(false)
        put :update, {:id => fuel_issued.to_param, :fuel_issued => { "depot_fuel_id" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested fuel_issued" do
      fuel_issued = FuelIssued.create! valid_attributes
      expect {
        delete :destroy, {:id => fuel_issued.to_param}, valid_session
      }.to change(FuelIssued, :count).by(-1)
    end

    it "redirects to the fuel_issueds list" do
      fuel_issued = FuelIssued.create! valid_attributes
      delete :destroy, {:id => fuel_issued.to_param}, valid_session
      response.should redirect_to(fuel_issueds_url)
    end
  end

end
