require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe VehicleCardsController do

  # This should return the minimal set of attributes required to create a valid
  # VehicleCard. As you add validations to VehicleCard, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "vehicle_id" => "1" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # VehicleCardsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all vehicle_cards as @vehicle_cards" do
      vehicle_card = VehicleCard.create! valid_attributes
      get :index, {}, valid_session
      assigns(:vehicle_cards).should eq([vehicle_card])
    end
  end

  describe "GET show" do
    it "assigns the requested vehicle_card as @vehicle_card" do
      vehicle_card = VehicleCard.create! valid_attributes
      get :show, {:id => vehicle_card.to_param}, valid_session
      assigns(:vehicle_card).should eq(vehicle_card)
    end
  end

  describe "GET new" do
    it "assigns a new vehicle_card as @vehicle_card" do
      get :new, {}, valid_session
      assigns(:vehicle_card).should be_a_new(VehicleCard)
    end
  end

  describe "GET edit" do
    it "assigns the requested vehicle_card as @vehicle_card" do
      vehicle_card = VehicleCard.create! valid_attributes
      get :edit, {:id => vehicle_card.to_param}, valid_session
      assigns(:vehicle_card).should eq(vehicle_card)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new VehicleCard" do
        expect {
          post :create, {:vehicle_card => valid_attributes}, valid_session
        }.to change(VehicleCard, :count).by(1)
      end

      it "assigns a newly created vehicle_card as @vehicle_card" do
        post :create, {:vehicle_card => valid_attributes}, valid_session
        assigns(:vehicle_card).should be_a(VehicleCard)
        assigns(:vehicle_card).should be_persisted
      end

      it "redirects to the created vehicle_card" do
        post :create, {:vehicle_card => valid_attributes}, valid_session
        response.should redirect_to(VehicleCard.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved vehicle_card as @vehicle_card" do
        # Trigger the behavior that occurs when invalid params are submitted
        VehicleCard.any_instance.stub(:save).and_return(false)
        post :create, {:vehicle_card => { "vehicle_id" => "invalid value" }}, valid_session
        assigns(:vehicle_card).should be_a_new(VehicleCard)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        VehicleCard.any_instance.stub(:save).and_return(false)
        post :create, {:vehicle_card => { "vehicle_id" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested vehicle_card" do
        vehicle_card = VehicleCard.create! valid_attributes
        # Assuming there are no other vehicle_cards in the database, this
        # specifies that the VehicleCard created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        VehicleCard.any_instance.should_receive(:update).with({ "vehicle_id" => "1" })
        put :update, {:id => vehicle_card.to_param, :vehicle_card => { "vehicle_id" => "1" }}, valid_session
      end

      it "assigns the requested vehicle_card as @vehicle_card" do
        vehicle_card = VehicleCard.create! valid_attributes
        put :update, {:id => vehicle_card.to_param, :vehicle_card => valid_attributes}, valid_session
        assigns(:vehicle_card).should eq(vehicle_card)
      end

      it "redirects to the vehicle_card" do
        vehicle_card = VehicleCard.create! valid_attributes
        put :update, {:id => vehicle_card.to_param, :vehicle_card => valid_attributes}, valid_session
        response.should redirect_to(vehicle_card)
      end
    end

    describe "with invalid params" do
      it "assigns the vehicle_card as @vehicle_card" do
        vehicle_card = VehicleCard.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        VehicleCard.any_instance.stub(:save).and_return(false)
        put :update, {:id => vehicle_card.to_param, :vehicle_card => { "vehicle_id" => "invalid value" }}, valid_session
        assigns(:vehicle_card).should eq(vehicle_card)
      end

      it "re-renders the 'edit' template" do
        vehicle_card = VehicleCard.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        VehicleCard.any_instance.stub(:save).and_return(false)
        put :update, {:id => vehicle_card.to_param, :vehicle_card => { "vehicle_id" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested vehicle_card" do
      vehicle_card = VehicleCard.create! valid_attributes
      expect {
        delete :destroy, {:id => vehicle_card.to_param}, valid_session
      }.to change(VehicleCard, :count).by(-1)
    end

    it "redirects to the vehicle_cards list" do
      vehicle_card = VehicleCard.create! valid_attributes
      delete :destroy, {:id => vehicle_card.to_param}, valid_session
      response.should redirect_to(vehicle_cards_url)
    end
  end

end
