require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe VehicleFinesController do

  # This should return the minimal set of attributes required to create a valid
  # VehicleFine. As you add validations to VehicleFine, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "code" => "MyString" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # VehicleFinesController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all vehicle_fines as @vehicle_fines" do
      vehicle_fine = VehicleFine.create! valid_attributes
      get :index, {}, valid_session
      assigns(:vehicle_fines).should eq([vehicle_fine])
    end
  end

  describe "GET show" do
    it "assigns the requested vehicle_fine as @vehicle_fine" do
      vehicle_fine = VehicleFine.create! valid_attributes
      get :show, {:id => vehicle_fine.to_param}, valid_session
      assigns(:vehicle_fine).should eq(vehicle_fine)
    end
  end

  describe "GET new" do
    it "assigns a new vehicle_fine as @vehicle_fine" do
      get :new, {}, valid_session
      assigns(:vehicle_fine).should be_a_new(VehicleFine)
    end
  end

  describe "GET edit" do
    it "assigns the requested vehicle_fine as @vehicle_fine" do
      vehicle_fine = VehicleFine.create! valid_attributes
      get :edit, {:id => vehicle_fine.to_param}, valid_session
      assigns(:vehicle_fine).should eq(vehicle_fine)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new VehicleFine" do
        expect {
          post :create, {:vehicle_fine => valid_attributes}, valid_session
        }.to change(VehicleFine, :count).by(1)
      end

      it "assigns a newly created vehicle_fine as @vehicle_fine" do
        post :create, {:vehicle_fine => valid_attributes}, valid_session
        assigns(:vehicle_fine).should be_a(VehicleFine)
        assigns(:vehicle_fine).should be_persisted
      end

      it "redirects to the created vehicle_fine" do
        post :create, {:vehicle_fine => valid_attributes}, valid_session
        response.should redirect_to(VehicleFine.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved vehicle_fine as @vehicle_fine" do
        # Trigger the behavior that occurs when invalid params are submitted
        VehicleFine.any_instance.stub(:save).and_return(false)
        post :create, {:vehicle_fine => { "code" => "invalid value" }}, valid_session
        assigns(:vehicle_fine).should be_a_new(VehicleFine)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        VehicleFine.any_instance.stub(:save).and_return(false)
        post :create, {:vehicle_fine => { "code" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested vehicle_fine" do
        vehicle_fine = VehicleFine.create! valid_attributes
        # Assuming there are no other vehicle_fines in the database, this
        # specifies that the VehicleFine created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        VehicleFine.any_instance.should_receive(:update).with({ "code" => "MyString" })
        put :update, {:id => vehicle_fine.to_param, :vehicle_fine => { "code" => "MyString" }}, valid_session
      end

      it "assigns the requested vehicle_fine as @vehicle_fine" do
        vehicle_fine = VehicleFine.create! valid_attributes
        put :update, {:id => vehicle_fine.to_param, :vehicle_fine => valid_attributes}, valid_session
        assigns(:vehicle_fine).should eq(vehicle_fine)
      end

      it "redirects to the vehicle_fine" do
        vehicle_fine = VehicleFine.create! valid_attributes
        put :update, {:id => vehicle_fine.to_param, :vehicle_fine => valid_attributes}, valid_session
        response.should redirect_to(vehicle_fine)
      end
    end

    describe "with invalid params" do
      it "assigns the vehicle_fine as @vehicle_fine" do
        vehicle_fine = VehicleFine.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        VehicleFine.any_instance.stub(:save).and_return(false)
        put :update, {:id => vehicle_fine.to_param, :vehicle_fine => { "code" => "invalid value" }}, valid_session
        assigns(:vehicle_fine).should eq(vehicle_fine)
      end

      it "re-renders the 'edit' template" do
        vehicle_fine = VehicleFine.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        VehicleFine.any_instance.stub(:save).and_return(false)
        put :update, {:id => vehicle_fine.to_param, :vehicle_fine => { "code" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested vehicle_fine" do
      vehicle_fine = VehicleFine.create! valid_attributes
      expect {
        delete :destroy, {:id => vehicle_fine.to_param}, valid_session
      }.to change(VehicleFine, :count).by(-1)
    end

    it "redirects to the vehicle_fines list" do
      vehicle_fine = VehicleFine.create! valid_attributes
      delete :destroy, {:id => vehicle_fine.to_param}, valid_session
      response.should redirect_to(vehicle_fines_url)
    end
  end

end
