require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe VehicleRoadTaxesController do

  # This should return the minimal set of attributes required to create a valid
  # VehicleRoadTax. As you add validations to VehicleRoadTax, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "vehicle_id" => "1" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # VehicleRoadTaxesController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all vehicle_road_taxes as @vehicle_road_taxes" do
      vehicle_road_tax = VehicleRoadTax.create! valid_attributes
      get :index, {}, valid_session
      assigns(:vehicle_road_taxes).should eq([vehicle_road_tax])
    end
  end

  describe "GET show" do
    it "assigns the requested vehicle_road_tax as @vehicle_road_tax" do
      vehicle_road_tax = VehicleRoadTax.create! valid_attributes
      get :show, {:id => vehicle_road_tax.to_param}, valid_session
      assigns(:vehicle_road_tax).should eq(vehicle_road_tax)
    end
  end

  describe "GET new" do
    it "assigns a new vehicle_road_tax as @vehicle_road_tax" do
      get :new, {}, valid_session
      assigns(:vehicle_road_tax).should be_a_new(VehicleRoadTax)
    end
  end

  describe "GET edit" do
    it "assigns the requested vehicle_road_tax as @vehicle_road_tax" do
      vehicle_road_tax = VehicleRoadTax.create! valid_attributes
      get :edit, {:id => vehicle_road_tax.to_param}, valid_session
      assigns(:vehicle_road_tax).should eq(vehicle_road_tax)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new VehicleRoadTax" do
        expect {
          post :create, {:vehicle_road_tax => valid_attributes}, valid_session
        }.to change(VehicleRoadTax, :count).by(1)
      end

      it "assigns a newly created vehicle_road_tax as @vehicle_road_tax" do
        post :create, {:vehicle_road_tax => valid_attributes}, valid_session
        assigns(:vehicle_road_tax).should be_a(VehicleRoadTax)
        assigns(:vehicle_road_tax).should be_persisted
      end

      it "redirects to the created vehicle_road_tax" do
        post :create, {:vehicle_road_tax => valid_attributes}, valid_session
        response.should redirect_to(VehicleRoadTax.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved vehicle_road_tax as @vehicle_road_tax" do
        # Trigger the behavior that occurs when invalid params are submitted
        VehicleRoadTax.any_instance.stub(:save).and_return(false)
        post :create, {:vehicle_road_tax => { "vehicle_id" => "invalid value" }}, valid_session
        assigns(:vehicle_road_tax).should be_a_new(VehicleRoadTax)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        VehicleRoadTax.any_instance.stub(:save).and_return(false)
        post :create, {:vehicle_road_tax => { "vehicle_id" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested vehicle_road_tax" do
        vehicle_road_tax = VehicleRoadTax.create! valid_attributes
        # Assuming there are no other vehicle_road_taxes in the database, this
        # specifies that the VehicleRoadTax created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        VehicleRoadTax.any_instance.should_receive(:update).with({ "vehicle_id" => "1" })
        put :update, {:id => vehicle_road_tax.to_param, :vehicle_road_tax => { "vehicle_id" => "1" }}, valid_session
      end

      it "assigns the requested vehicle_road_tax as @vehicle_road_tax" do
        vehicle_road_tax = VehicleRoadTax.create! valid_attributes
        put :update, {:id => vehicle_road_tax.to_param, :vehicle_road_tax => valid_attributes}, valid_session
        assigns(:vehicle_road_tax).should eq(vehicle_road_tax)
      end

      it "redirects to the vehicle_road_tax" do
        vehicle_road_tax = VehicleRoadTax.create! valid_attributes
        put :update, {:id => vehicle_road_tax.to_param, :vehicle_road_tax => valid_attributes}, valid_session
        response.should redirect_to(vehicle_road_tax)
      end
    end

    describe "with invalid params" do
      it "assigns the vehicle_road_tax as @vehicle_road_tax" do
        vehicle_road_tax = VehicleRoadTax.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        VehicleRoadTax.any_instance.stub(:save).and_return(false)
        put :update, {:id => vehicle_road_tax.to_param, :vehicle_road_tax => { "vehicle_id" => "invalid value" }}, valid_session
        assigns(:vehicle_road_tax).should eq(vehicle_road_tax)
      end

      it "re-renders the 'edit' template" do
        vehicle_road_tax = VehicleRoadTax.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        VehicleRoadTax.any_instance.stub(:save).and_return(false)
        put :update, {:id => vehicle_road_tax.to_param, :vehicle_road_tax => { "vehicle_id" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested vehicle_road_tax" do
      vehicle_road_tax = VehicleRoadTax.create! valid_attributes
      expect {
        delete :destroy, {:id => vehicle_road_tax.to_param}, valid_session
      }.to change(VehicleRoadTax, :count).by(-1)
    end

    it "redirects to the vehicle_road_taxes list" do
      vehicle_road_tax = VehicleRoadTax.create! valid_attributes
      delete :destroy, {:id => vehicle_road_tax.to_param}, valid_session
      response.should redirect_to(vehicle_road_taxes_url)
    end
  end

end
